# Docker Compose File for Application Container with Docker bindings
version: '3.8'

services:
  dev:
    image: ghcr.io/octodemo/container-nodejs-development:base-latest
    command: sleep infinity

    ports:
      - "8080:8080"

    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

      - type: bind
        source: /usr/bin/docker
        target: /usr/bin/docker

      - type: bind
        source: /usr/local/bin/docker-compose
        target: /usr/local/bin/docker-compose

  db:
    image: postgres:12
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

    volumes:
      - type: bind
        source: ../database/db-scripts
        target: /docker-entrypoint-initdb.d
        consistency: consistent

      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        consistency: consistent

volumes:
  postgres-data:
